version: '3'
services:
    argon-db:
        container_name: db
        image: postgres:14
        volumes:
            - argon-db-data:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: argon
            POSTGRES_USER: argon_admin
            POSTGRES_PASSWORD: password123
        ports:
            - 5432:5432
    argon-backend:
        container_name: be
        image: argon-backend
        depends_on:
            - argon-db
        environment:
            - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/argon
            - SPRING_DATASOURCE_USERNAME=argon_admin
            - SPRING_DATASOURCE_PASSWORD=password123
        ports:
            - 8080:8080
    argon-frontend:
        container_name: fe
        image: argon-frontend
        depends_on:
            - argon-backend
        environment:
            - API_URL=http://localhost:8080/
            - PRODUCTION=true
        ports:
            - 80:80
volumes:
    argon-db-data:
